### PR TITLE
Fix #76: Add name to input fields

### LINKED ISSUE #76: Add `name` to input fields
I have been doing some testing this week with my and form input.  For `inline` input when I submit a form only 1 of the input values is being sent in the form submit.

Just this value is being sent.
image

IF I add `name` props to the rest of the input fields then I can see the rest of the values in Form Submit.

image

This would be preferable so in `inline` mode I can just get the selected color.

### PR DESCRIPTION
**Pull request by melloware**
Fix #76: Add name to input fields

### CODE REVIEW

**Review by mdbassit — CHANGES_REQUESTED** [review]
Void elements (like `input`) should not have a closing tag or self-closing slash in HTML. That's a relic from XHTML. 

https://html.spec.whatwg.org/multipage/syntax.html#void-elements

Could you please remove them?

**Comment by melloware** [comment]
I will remove. I am a relic I still work I. xHTML so when I see hanging tags it looks so odd to me but you are right the HTML spec says they are not needed!

**Comment by melloware** [comment]
slashes removed!

**Review by mdbassit — APPROVED** [review]
Great, thank you!

**Pull request merged**
